[project]
id = "linhas-app"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
port = 54323
api_url = "http://localhost"

[ingest]
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://linhas.app"]
jwt_expiry = 3600
enable_signup = true
anonymous_sign_ins = true

[edge_runtime]
policy = "per_worker"

[analytics]
enabled = false
